export const DSO_DAYS_PERIOD = 30;
export const AT_RISK_DSO_DAYS_THRESHOLD = 30;
export const AT_RISK_DSO_MILLISECONDS_THRESHOLD = 30 * 24 * 60 * 60 * 1000;
export const LARGE_OUTSTANDING_EUROS_THRESHOLD = 5000;
export const AT_RISK_OUTSTANDING_EUROS_THRESHOLD = 10000;