export const DSO_DAYS_PERIOD = 30;
export const AT_RISK_DSO_DAYS_THRESHOLD = 30;
export const AT_RISK_DSO_MILLISECONDS_THRESHOLD = 30 * 24 * 60 * 60 * 1000;
export const LARGE_OUTSTANDING_EUROS_THRESHOLD = 5000;
export const AT_RISK_OUTSTANDING_EUROS_THRESHOLD = 10000;

export const INVOICE_FORM_CONSTANTS = {
  SEARCH_DEBOUNCE_MS: 300,
  MIN_SEARCH_LENGTH: 3,
  MIN_PRODUCT_SEARCH_LENGTH: 2,
  DEFAULT_QUANTITY: 1,
} as const;